services:
  orders-service:
    build:
      context: ./orders-service
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_NAME=orderdb
      - CORS_ORIGIN=http://localhost:4200,http://localhost:3000
      - JWT_SECRET=topsecret
      - TRACE_EXPORTER_URL=http://jaeger:4318/v1/traces
    depends_on:
      jaeger:
        condition: service_started
      postgres:
        condition: service_healthy

  orders-ui:
    build:
      context: ./orders-ui
      dockerfile: Dockerfile
    ports:
      - "3001:80"
    depends_on:
      orders-service:
        condition: service_started

  postgres:
    image: postgres:17-bookworm
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=orderdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  jaeger:
    image: jaegertracing/all-in-one:1.57
    ports:
      - "16686:16686"
      - "4318:4318"
      - "5778:5778"
      - "9411:9411"

volumes:
  postgres_data:
